redis:
    container_name: redis
    image: mmessenger/mredis
    restart: always
    volumes:
      - ${MMSG_REDIS_DATA}:/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    ports:
      - "6379:6379"
